### ISSUE TITLE
Compilation errors in node 8.2.1 while 8.9.1 works fine

### ISSUE THREAD

**Issue by adambabik** [nodejs/node-addon-api#191]
Hi,

I am trying to build a native module for node v8.2.1. It's because it must work with electron. I managed to do so with v8.9.1 as it's the newest LTS, however, I am getting a lot of errors when trying to build against node v8.2.1.

I am using node-addon-api in version 1.1.0.

```
In file included from ../src/status.cc:1:
/Users/adamb/repos/status-node-ethereum/node_modules/node-addon-api/napi.h:830:7: error: unknown type name 'napi_deferred'
      napi_deferred _deferred;
      ^
In file included from ../src/status.cc:1:
In file included from /Users/adamb/repos/status-node-ethereum/node_modules/node-addon-api/napi.h:1484:
/Users/adamb/repos/status-node-ethereum/node_modules/node-addon-api/napi-inl.h:345:24: error: use of undeclared identifier 'napi_is_promise'
  napi_status status = napi_is_promise(_env, _value, &result);
                       ^
/Users/adamb/repos/status-node-ethereum/node_modules/node-addon-api/napi-inl.h:428:24: error: use of undeclared identifier 'napi_create_double'
  napi_status status = napi_create_double(env, val, &value);
                       ^
/Users/adamb/repos/status-node-ethereum/node_modules/node-addon-api/napi-inl.h:1332:20: error: use of undeclared identifier 'NAPI_AUTO_LENGTH'
    env, utf8name, NAPI_AUTO_LENGTH, CbData::Wrapper, callbackData, &value);
                   ^
/Users/adamb/repos/status-node-ethereum/node_modules/node-addon-api/napi-inl.h:1396:24: error: no matching function for call to 'napi_make_callback'
  napi_status status = napi_make_callback(
                       ^~~~~~~~~~~~~~~~~~
/Users/adamb/.node-gyp/8.2.1/include/node/node_api.h:312:25: note: candidate function not viable: requires 6 arguments, but 7 were provided
NAPI_EXTERN napi_status napi_make_callback(napi_env env,
                        ^
In file included from ../src/status.cc:1:
In file included from /Users/adamb/repos/status-node-ethereum/node_modules/node-addon-api/napi.h:1484:
/Users/adamb/repos/status-node-ethereum/node_modules/node-addon-api/napi-inl.h:1611:20: error: no matching function for call to 'napi_create_type_error'
          status = napi_create_type_error(env, nullptr, message, &error);
                   ^~~~~~~~~~~~~~~~~~~~~~
/Users/adamb/.node-gyp/8.2.1/include/node/node_api.h:156:25: note: candidate function not viable: requires 3 arguments, but 4 were provided
NAPI_EXTERN napi_status napi_create_type_error(napi_env env,
                        ^
In file included from ../src/status.cc:1:
In file included from /Users/adamb/repos/status-node-ethereum/node_modules/node-addon-api/napi.h:1484:
/Users/adamb/repos/status-node-ethereum/node_modules/node-addon-api/napi-inl.h:1614:20: error: no matching function for call to 'napi_create_error'
          status = napi_create_error(env, nullptr,  message, &error);
                   ^~~~~~~~~~~~~~~~~
/Users/adamb/.node-gyp/8.2.1/include/node/node_api.h:153:25: note: candidate function not viable: requires 3 arguments, but 4 were provided
NAPI_EXTERN napi_status napi_create_error(napi_env env,
                        ^
In file included from ../src/status.cc:1:
In file included from /Users/adamb/repos/status-node-ethereum/node_modules/node-addon-api/napi.h:1484:
/Users/adamb/repos/status-node-ethereum/node_modules/node-addon-api/napi-inl.h:1626:10: error: no matching function for call to 'New'
  return Error::New<Error>(env, message, std::strlen(message), napi_create_error);
         ^~~~~~~~~~~~~~~~~
/Users/adamb/repos/status-node-ethereum/node_modules/node-addon-api/napi.h:1117:19: note: candidate function not viable: no known conversion from
      'napi_status (napi_env, napi_value, napi_value *)' (aka 'napi_status (napi_env__ *, napi_value__ *, napi_value__ **)') to 'create_error_fn' (aka 'napi_status (*)(napi_env__ *,
      napi_value__ *, napi_value__ *, napi_value__ **)') for 4th argument
    static TError New(napi_env env,
                  ^
```

This is just a fragment of all errors.

Is there a `node-addon-api` version that is supposed to work with 8.2.1 or that version is not supported anymore?

**Comment by mhdawson** [comment]
We made some breaking changes in N-API in 8.6 (the last expected) which are likely related.  

I know that @gabrielschulhof has been  looking at backwards compatibility and I remember he mentioned issues with earlier versions of 8.x.  What I can't remember is if it was just that we could not address those earlier versions of 8.x or if he had some ideas.  @gabrielschulhof can you comment.

**Comment by mhdawson** [comment]
As context its actually easier for us in 4.x and 6.x since they don't have an implementation of N-API so providing one though the npm module is straight forward.  For 8.X there are possible conflicts with the version that was present in those Node.js versions.

**Comment by adambabik** [comment]
@mhdawson thanks for the quick response! Appreciate it! I will wait a bit for @gabrielschulhof's comment.

In the meantime, as you suggested, I tried to go with node v7.9.0 as it's the one used by the latest stable electron release. I assume it's pretty close to 6.x. It compiled correctly, but when I tried to execute JS code using my native module, I got:
```
Error: dlopen(/Users/adamb/repos/status-node-ethereum/build/Release/binding.node, 1): Symbol not found: _napi_create_type_error
```.

**Comment by andreek** [comment]
@adambabik maybe ```binding.gyp``` is missing ```'dependencies': ["<!(node -p \"require('node-addon-api').gyp\")"]```. I've got the same error some days ago. Did you use the conversion tool?

**Comment by adambabik** [comment]
@andreek I had it included for sure but I didn't use any conversion tool as far as I remember. I followed `N-API` examples from the beginning so I thought I didn't need it. 

Finally, I decided to go with raw C++ code and it worked fine. It wasn't a complicated addon anyway.

**Comment by mhdawson** [comment]
@adambabik sorry we could not answer your questions quickly enough to get you going.  Is electron still at 8.2.1 or has it moved up to a newer Node.js version ?

**Comment by adambabik** [comment]
@mhdawson no worries! As I said, my module was simple enough so I could write raw C++ code. As far as I know, they will continue building version 1.8.2 on node 8.2.1 :(

**Comment by mhdawson** [comment]
@gabrielschulhof you made a change to fix compatibility with earlier 8.X versions. Would it have addressed this issue?

**Comment by NicoAiko** [comment]
I get these errors on Node v8.11.1... Is there a way to fix this?

**Comment by NickNaso** [comment]
@NicoAiko Could you post your code or maybe a link  to it?

**Comment by NicoAiko** [comment]
Actually, I can’t, because I’m not actively working with node-addon-api.
One of my dependencies, namely discord-rpc, uses it, but I found out that it is optional and can be ignored.

The version was, however, the latest.

The errors look just like the one in the first post of this issue.

**Comment by NickNaso** [comment]
Hi @NicoAiko  I taken a look at discord-rpc and this modul uses as dependencies only one module implemented through **node-addon-api** ([register-scheme](https://github.com/devsnek/node-register-scheme)), while the others are implemented with the classical V8 API or with NAN. 
I tried to install the reported module and it worked. Which operating system are you using? Could you attach the error log of your installation?

**Comment by NicoAiko** [comment]
I use macOS High Sierra 10.13.4

And yes, register-scheme is the one. That failed for me. Unfortunately, I can’t find the exact error log.

I only have the one that is saved from npm-debug.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node@8/8.11.1/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'rebuild',
1 verbose cli   'bufferutil@3.0.4',
1 verbose cli   'erlpack@0.1.0',
1 verbose cli   'fsevents@1.1.3',
1 verbose cli   'node-opus@0.2.7',
1 verbose cli   'ref@1.3.5',
1 verbose cli   'register-scheme@0.0.1',
1 verbose cli   'sodium@2.0.3',
1 verbose cli   'uws@9.148.0',
1 verbose cli   'zlib-sync@0.1.4' ]
2 info using npm@6.0.0
3 info using node@v8.11.1
4 info readInstalled object
5 verbose rebuild path, id [ '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/erlpack',
5 verbose rebuild   'erlpack@0.1.0' ]
6 verbose rebuild path, id [ '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/ref',
6 verbose rebuild   'ref@1.3.5' ]
7 verbose rebuild path, id [ '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/register-scheme',
7 verbose rebuild   'register-scheme@0.0.1' ]
8 verbose rebuild path, id [ '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/sodium',
8 verbose rebuild   'sodium@2.0.3' ]
9 verbose rebuild path, id [ '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/uws',
9 verbose rebuild   'uws@9.148.0' ]
10 verbose rebuild path, id [ '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/zlib-sync',
10 verbose rebuild   'zlib-sync@0.1.4' ]
11 verbose rebuild path, id [ '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/bufferutil',
11 verbose rebuild   'bufferutil@3.0.4' ]
12 verbose rebuild path, id [ '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/node-opus',
12 verbose rebuild   'node-opus@0.2.7' ]
13 verbose rebuild path, id [ '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/fsevents',
13 verbose rebuild   'fsevents@1.1.3' ]
14 silly rebuild set [ '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/erlpack',
14 silly rebuild set   '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/ref',
14 silly rebuild set   '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/register-scheme',
14 silly rebuild set   '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/sodium',
14 silly rebuild set   '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/uws',
14 silly rebuild set   '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/zlib-sync',
14 silly rebuild set   '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/bufferutil',
14 silly rebuild set   '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/node-opus',
14 silly rebuild set   '/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/fsevents' ]
15 info build /Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/erlpack
16 info lifecycle erlpack@0.1.0~preinstall: erlpack@0.1.0
17 info linkStuff erlpack@0.1.0
18 silly linkStuff erlpack@0.1.0 has /Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules as its parent node_modules
19 info lifecycle erlpack@0.1.0~install: erlpack@0.1.0
20 verbose lifecycle erlpack@0.1.0~install: unsafe-perm in lifecycle true
21 verbose lifecycle erlpack@0.1.0~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/erlpack/node_modules/.bin:/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/.bin:/usr/local/opt/php@7.1/sbin:/usr/local/opt/php@7.1/bin:/Users/ooBlankedOutoo/.gem/ruby/2.3.0/bin:/usr/local/bin:/usr/local/opt/node@8/bin:/usr/local/sbin:/usr/local/mysql-5.7.10-osx10.9-x86_64/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/opt/php@7.1/sbin:/usr/local/opt/php@7.1/bin:/Users/ooBlankedOutoo/.gem/ruby/2.3.0/bin:/usr/local/opt/node@8/bin:/usr/local/sbin:/usr/local/mysql-5.7.10-osx10.9-x86_64/bin
22 verbose lifecycle erlpack@0.1.0~install: CWD: /Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/erlpack
23 silly lifecycle erlpack@0.1.0~install: Args: [ '-c', 'node-gyp rebuild' ]
24 silly lifecycle erlpack@0.1.0~install: Returned: code: 0  signal: null
25 info lifecycle erlpack@0.1.0~postinstall: erlpack@0.1.0
26 info build /Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/ref
27 info lifecycle ref@1.3.5~preinstall: ref@1.3.5
28 info linkStuff ref@1.3.5
29 silly linkStuff ref@1.3.5 has /Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules as its parent node_modules
30 verbose rebuildBundles [ 'debug' ]
31 info lifecycle ref@1.3.5~install: ref@1.3.5
32 verbose lifecycle ref@1.3.5~install: unsafe-perm in lifecycle true
33 verbose lifecycle ref@1.3.5~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/ref/node_modules/.bin:/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/.bin:/usr/local/opt/php@7.1/sbin:/usr/local/opt/php@7.1/bin:/Users/ooBlankedOutoo/.gem/ruby/2.3.0/bin:/usr/local/bin:/usr/local/opt/node@8/bin:/usr/local/sbin:/usr/local/mysql-5.7.10-osx10.9-x86_64/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/opt/php@7.1/sbin:/usr/local/opt/php@7.1/bin:/Users/ooBlankedOutoo/.gem/ruby/2.3.0/bin:/usr/local/opt/node@8/bin:/usr/local/sbin:/usr/local/mysql-5.7.10-osx10.9-x86_64/bin
34 verbose lifecycle ref@1.3.5~install: CWD: /Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/ref
35 silly lifecycle ref@1.3.5~install: Args: [ '-c', 'node-gyp rebuild' ]
36 silly lifecycle ref@1.3.5~install: Returned: code: 0  signal: null
37 info lifecycle ref@1.3.5~postinstall: ref@1.3.5
38 info build /Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/register-scheme
39 info lifecycle register-scheme@0.0.1~preinstall: register-scheme@0.0.1
40 info linkStuff register-scheme@0.0.1
41 silly linkStuff register-scheme@0.0.1 has /Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules as its parent node_modules
42 info lifecycle register-scheme@0.0.1~install: register-scheme@0.0.1
43 verbose lifecycle register-scheme@0.0.1~install: unsafe-perm in lifecycle true
44 verbose lifecycle register-scheme@0.0.1~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/register-scheme/node_modules/.bin:/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/.bin:/usr/local/opt/php@7.1/sbin:/usr/local/opt/php@7.1/bin:/Users/ooBlankedOutoo/.gem/ruby/2.3.0/bin:/usr/local/bin:/usr/local/opt/node@8/bin:/usr/local/sbin:/usr/local/mysql-5.7.10-osx10.9-x86_64/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/opt/php@7.1/sbin:/usr/local/opt/php@7.1/bin:/Users/ooBlankedOutoo/.gem/ruby/2.3.0/bin:/usr/local/opt/node@8/bin:/usr/local/sbin:/usr/local/mysql-5.7.10-osx10.9-x86_64/bin
45 verbose lifecycle register-scheme@0.0.1~install: CWD: /Users/ooBlankedOutoo/Development/ooBlankedOutoo/node_modules/register-scheme
46 silly lifecycle register-scheme@0.0.1~install: Args: [ '-c', 'node-gyp rebuild' ]
47 silly lifecycle register-scheme@0.0.1~install: Returned: code: 1  signal: null
48 info lifecycle register-scheme@0.0.1~install: Failed to exec install script
49 verbose stack Error: register-scheme@0.0.1 install: `node-gyp rebuild`
49 verbose stack Exit status 1
49 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
49 verbose stack     at emitTwo (events.js:126:13)
49 verbose stack     at EventEmitter.emit (events.js:214:7)
49 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
49 verbose stack     at emitTwo (events.js:126:13)
49 verbose stack     at ChildProcess.emit (events.js:214:7)
49 verbose stack     at maybeClose (internal/child_process.js:925:16)
49 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
50 verbose pkgid register-scheme@0.0.1
51 verbose cwd /Users/ooBlankedOutoo/Development/ooBlankedOutoo
52 verbose Darwin 17.5.0
53 verbose argv "/usr/local/Cellar/node@8/8.11.1/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "rebuild" "bufferutil@3.0.4" "erlpack@0.1.0" "fsevents@1.1.3" "node-opus@0.2.7" "ref@1.3.5" "register-scheme@0.0.1" "sodium@2.0.3" "uws@9.148.0" "zlib-sync@0.1.4"
54 verbose node v8.11.1
55 verbose npm  v6.0.0
56 error code ELIFECYCLE
57 error errno 1
58 error register-scheme@0.0.1 install: `node-gyp rebuild`
58 error Exit status 1
59 error Failed at the register-scheme@0.0.1 install script.
59 error This is probably not a problem with npm. There is likely additional logging output above.
60 verbose exit [ 1, true ]
```

**Comment by NickNaso** [comment]
@NicoAiko Any news? At the end you solved the problem?

**Comment by NickNaso** [comment]
Hi everyone,
I don't know if the problem described in the issue has been solved. Could someone update about that? 
Could be possible close the issue if the problem has been fixed?

**Comment by mhdawson** [comment]
Node.js 8.x is not long out of LTS and there was no response to @NickNaso question. Closing out. Please let us know if this is not the right thing to do.
