### ISSUE TITLE
Following instructions, depending module do not compile on Node 6.11 

### ISSUE THREAD

**Issue by mcollina** [nodejs/node-addon-api#97]
```
CXX(target) Release/obj.target/node-api/node_modules/node-addon-api/src/node_api.o
In file included from ../node_modules/node-addon-api/src/node_api.cc:20:
In file included from ../node_modules/node-addon-api/src/node_internals.h:8:
../node_modules/node-addon-api/src/util-inl.h:9:8: error: use of undeclared identifier 'Napi'
inline Napi::String OneByteString(v8::Isolate* isolate,
       ^
../node_modules/node-addon-api/src/util-inl.h:12:10: error: no viable conversion from returned value of type 'MaybeLocal<v8::String>' to function return type 'int'
  return v8::String::NewFromOneByte(isolate,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/node-addon-api/src/util-inl.h:18:8: error: use of undeclared identifier 'Napi'
inline Napi::String OneByteString(v8::Isolate* isolate,
       ^
../node_modules/node-addon-api/src/util-inl.h:21:10: error: no viable conversion from returned value of type 'MaybeLocal<v8::String>' to function return type 'int'
  return v8::String::NewFromOneByte(isolate,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

(and others)

Launching `npm test`  from this module works, so maybe there is something to be updated in the README about the instructions on how to update `binding.gyp`.

Here is my `binding.gyp`:

```
{
  "targets": [
    {
      "target_name": "native-hdr-histogram",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "sources": [
        "src/hdr_encoding.h",
        "src/hdr_encoding.c",
        "src/hdr_histogram.h",
        "src/hdr_histogram.c",
        "src/hdr_histogram_log.h",
        "src/hdr_histogram_log.c",
        "hdr_histogram_wrap.cc",
        "histogram.cc"
      ],
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")",
        "src/"
      ],
      "dependencies": [
        "<(module_root_dir)/zlib/zlib.gyp:zlib",
        "<!(node -p \"require('node-addon-api').gyp\")"
      ],
      'xcode_settings': {
        'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',
        'CLANG_CXX_LIBRARY': 'libc++',
        'MACOSX_DEPLOYMENT_TARGET': '10.7',
      },
      'msvs_settings': {
        'VCCLCompilerTool': { 'ExceptionHandling': 1 },
      }
    }
  ]
}
```

**Comment by jasongin** [comment]
Did you modify `util-inl.h`? It is not supposed to have any references to `Napi::String`.
https://github.com/nodejs/node-addon-api/blob/master/src/util-inl.h

**Comment by mcollina** [comment]
convert.js did it!

**Comment by mhdawson** [comment]
@mcollina so the conversion script ended up changing our own files as well ?  @sampsongao can you take a look to see how we can present that.

**Comment by mcollina** [comment]
@mhdawson yes. The problem is that the README suggest to:

```
node ./node_modules/node-addon-api/tools/conversion.js ./
```

But in https://github.com/nodejs/node-addon-api/blob/master/tools/conversion.js#L224 we do not blacklist for `node_modules`. I would recommend we depend on https://www.npmjs.com/package/glob, and even we ship the conversion tool as a separate npm package.

**Comment by mhdawson** [comment]
I think we can close this since https://github.com/nodejs/node-addon-api/pull/112 landed. Please let me know if that is not the case.
