### ISSUE TITLE
Build on Fedora 30 with gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1) fails

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#695]
```
make: Entering directory '/home/nix/node/node-addon-api/test/build'
  CXX(target) Release/obj.target/binding/arraybuffer.o
In file included from /home/nix/node/node-addon-api/napi.h:2404,
                 from ../arraybuffer.cc:1:
/home/nix/node/node-addon-api/napi-inl.h: In member function ‘void Napi::AsyncProgressWorker<T>::Signal() const’:
/home/nix/node/node-addon-api/napi-inl.h:4789:32: error: cannot convert ‘#‘addr_expr’ not supported by dump_type#<type error>’ to ‘Napi::AsyncProgressWorkerBase<void>*’
 4789 |   this->NonBlockingCall(nullptr);
      |                                ^
In file included from ../arraybuffer.cc:1:
/home/nix/node/node-addon-api/napi.h:2267:44: note:   initializing argument 'this' of ‘napi_status Napi::AsyncProgressWorkerBase<DataType>::NonBlockingCall(DataType*) [with DataType = void]’
 2267 |      napi_status NonBlockingCall(DataType* data);
      |                                  ~~~~~~~~~~^~~~
make: *** [binding.target.mk:174: Release/obj.target/binding/arraybuffer.o] Error 1
make: Leaving directory '/home/nix/node/node-addon-api/test/build'
```

**Comment by mhdawson** [comment]
Seems like the is failing, so not just that compiler. https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-LTS%20versions/700/

Seems to fail across versions.

**Comment by legendecas** [comment]
Seems gabriel submitted a fix on https://github.com/nodejs/node-addon-api/pull/696. I'm wondering that we have travis run gcc compilation on both Linux and macOS, it doesn't seem to be failed on the PR push checks 🤔. Is this only reproducible on specific gcc versions?

**Comment by richardlau** [comment]
> 
> 
> Seems gabriel submitted a fix on #696. I'm wondering that we have travis run gcc compilation on both Linux and macOS, it doesn't seem to be failed on the PR push checks 🤔. Is this only reproducible on specific gcc versions?

If you've not changed the default compiler on Travis then you'll probably be using either gcc 4.8.4 or 5 (depending on which Linux version you're running on). The Node.js CI will be using 6.3.0 at a minimum.
