### ISSUE TITLE
Compile failure after pull request #52

### ISSUE THREAD

**Issue by sampsongao** [nodejs/node-addon-api#61]
After the commit 09c7b71274cf3cf6d18a8c9ea15e5ebfab653645
, I see this build error when porting node-sqlite3 on linux.
```
../src/database.cc:24:6:   required from here
/home/sampsongao/node_api/sqlite3/node_modules/node-addon-api/napi-inl.h:51:21: error: void value not ignored as it ought to be
     return callback();
```

Any clue what is the fix here?

**Comment by jasongin** [comment]
What is at `database.cc:24` referenced in the error?

Looking through uses of `WrapCallback()` referenced in the error there, I do see what looks like a problem at `napi-inl.h:2435`. There should be a `return nullptr;` statement there. That could be the cause of that compile error.

**Comment by sampsongao** [comment]
```
    Napi::Function t = DefineClass(env, "Database", {
      InstanceMethod("close", &Database::Close),
      InstanceMethod("exec", &Database::Exec),
      InstanceMethod("wait", &Database::Wait),
      InstanceMethod("loadExtension", &Database::LoadExtension),
      InstanceMethod("serialize", &Database::Serialize),
      InstanceMethod("parallelize", &Database::Parallelize),
      InstanceMethod("configure", &Database::Configure),
      InstanceMethod("interrupt", &Database::Interrupt),
      InstanceAccessor("open", &Database::OpenGetter, nullptr),
    });        //  L. 24
```

**Comment by sampsongao** [comment]
Adding return nullptr after line 2435 works. Thanks!

**Comment by sampsongao** [comment]
Closed #62
