### ISSUE TITLE
Upgrading from v8.1.0 to v8.2.0 breaks compilation

### ISSUE THREAD

**Issue by ddolcimascolo** [nodejs/node-addon-api#1584]
Hi all,

In a Renovate MR upgrading node-addon-api to v8.2.0 (from v8.1.0) my build fails with lots of compilation errors in `napi.h`  :

```
In file included from ../src/supersecret.cc:3:                                                                                                                                                          
/data/dev/supersecret/node_modules/node-addon-api/napi.h:317:3: error: ‘node_api_nogc_env’ does not name a type                                                                                         
  317 |   node_api_nogc_env _env;                                                                                                                                                                       
      |   ^~~~~~~~~~~~~~~~~                                                                                                                                                                             
/data/dev/supersecret/node_modules/node-addon-api/napi.h:325:29: error: expected ‘)’ before ‘env’                                                                                                       
  325 |   BasicEnv(node_api_nogc_env env);                                                                                                                                                              
      |           ~                 ^~~~                                                                                                                                                                
      |                             )
/data/dev/supersecret/node_modules/node-addon-api/napi.h:326:12: error: expected type-specifier before ‘node_api_nogc_env’
  326 |   operator node_api_nogc_env() const;
      |            ^~~~~~~~~~~~~~~~~
/data/dev/supersecret/node_modules/node-addon-api/napi.h: In member function ‘bool Napi::BasicEnv::operator==(const Napi::BasicEnv&) const’:
/data/dev/supersecret/node_modules/node-addon-api/napi.h:335:12: error: ‘_env’ was not declared in this scope
  335 |     return _env == other._env;
      |            ^~~~
/data/dev/supersecret/node_modules/node-addon-api/napi.h:335:26: error: ‘const class Napi::BasicEnv’ has no member named ‘_env’
  335 |     return _env == other._env;
      |                          ^~~~
/data/dev/supersecret/node_modules/node-addon-api/napi.h: In member function ‘bool Napi::BasicEnv::operator==(std::nullptr_t) const’:
/data/dev/supersecret/node_modules/node-addon-api/napi.h:338:12: error: ‘_env’ was not declared in this scope
  338 |     return _env == nullptr;
      |            ^~~~
/data/dev/supersecret/node_modules/node-addon-api/napi.h: At global scope:
/data/dev/supersecret/node_modules/node-addon-api/napi.h:2467:32: error: ‘node_api_nogc_env’ has not been declared
 2467 |   static void FinalizeCallback(node_api_nogc_env env, void* data, void* hint);
      |                                ^~~~~~~~~~~~~~~~~
In file included from /data/dev/supersecret/node_modules/node-addon-api/napi.h:3257,
                 from ../src/supersecret.cc:3:
/data/dev/supersecret/node_modules/node-addon-api/napi-inl.h:38:13: error: variable or field ‘default_basic_finalizer’ declared void
   38 | inline void default_basic_finalizer(node_api_nogc_env /*env*/,
      |             ^~~~~~~~~~~~~~~~~~~~~~~
/data/dev/supersecret/node_modules/node-addon-api/napi-inl.h:38:37: error: ‘node_api_nogc_env’ was not declared in this scope
   38 | inline void default_basic_finalizer(node_api_nogc_env /*env*/,
      |                                     ^~~~~~~~~~~~~~~~~
/data/dev/supersecret/node_modules/node-addon-api/napi-inl.h:39:37: error: expected primary-expression before ‘void’
   39 |                                     void* data,
      |                                     ^~~~
/data/dev/supersecret/node_modules/node-addon-api/napi-inl.h:40:37: error: expected primary-expression before ‘void’
   40 |                                     void* /*hint*/) {
      |                                     ^~~~
/data/dev/supersecret/node_modules/node-addon-api/napi-inl.h:49:11: error: ‘node_api_nogc_finalize’ has not been declared
   49 |           node_api_nogc_finalize finalizer = default_basic_finalizer<FreeType>>
      |           ^~~~~~~~~~~~~~~~~~~~~~
/data/dev/supersecret/node_modules/node-addon-api/napi-inl.h:49:46: error: ‘default_basic_finalizer’ was not declared in this scope
   49 |           node_api_nogc_finalize finalizer = default_basic_finalizer<FreeType>>
```

For reference, my `binding.gyp` file:

```
{
  "targets": [
    {
      "target_name": "supersecret",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "sources": [
        "src/supersecret.cc"
      ],
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")"
      ]
    }
  ]
}
```

And I'm building with `node-gyp rebuild`

Do I need to change something with this release or is it something unexpected?

Thanks, and keep up the great work !

David

**Comment by e2e4e6** [comment]
I have the same problem.

**Comment by alek-wb** [comment]
Same problem. [cld](https://www.npmjs.com/package/cld) lib, which has `"node-addon-api": "*"` in dependencies fail to build on macos with similar errors that OP posted. 

Hardcoding `node-addon-api` to version 8.1.0 makes it work again.

**Comment by alek-wb** [comment]
This may be also useful for debugging - For me version 8.2.0 throws this error on node version `20.10.0`, but works on node `20.17.0`.

**Comment by ddolcimascolo** [comment]
Ah yes, I didn't give details on my setup. I'm indeed on Node 20.9.0, planning to upgrade to Node 22 when it turns LTS in a few weeks

**Comment by jvens** [comment]
I am seeing the exact same errors when attempting to build the `usb`  for an `arm` target with node version 18.17.1.

From the `package-lock.json` file:
```
    "node_modules/usb": {
      "version": "2.14.0",
      "resolved": "https://registry.npmjs.org/usb/-/usb-2.14.0.tgz",
      "integrity": "sha512-I3lzVOH21BsO6qPYvx1C7Ji08lbuM0qmsEtNGAphqlhNME5cz/vExY+jIXZl+HQIRybI/sTxdyLab5tALsL69w==",
      "hasInstallScript": true,
      "license": "MIT",
      "dependencies": {
        "@types/w3c-web-usb": "^1.0.6",
        "node-addon-api": "^8.0.0",
        "node-gyp-build": "^4.5.0"
      },
      "engines": {
        "node": ">=12.22.0 <13.0 || >=14.17.0"
      }
    },
    "node_modules/usb/node_modules/node-addon-api": {
      "version": "8.2.0",
      "resolved": "https://registry.npmjs.org/node-addon-api/-/node-addon-api-8.2.0.tgz",
      "integrity": "sha512-qnyuI2ROiCkye42n9Tj5aX1ns7rzj6n7zW1XReSnLSL9v/vbLeR6fJq6PU27YU/ICfYw6W7Ouk/N7cysWu/hlw==",
      "license": "MIT",
      "engines": {
        "node": "^18 || ^20 || >= 21"
      }
    },
```

Here is the full error output if that is helpful:
```
npm notice 
npm notice New major version of npm available! 9.6.7 -> 10.8.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.3
npm notice Run npm install -g npm@10.8.3 to update!
npm notice 
npm ERR! code 1
npm ERR! path /opt/pmc/global-gateway-server/node_modules/usb
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! make: Entering directory '/opt/pmc/global-gateway-server/node_modules/usb/build'
npm ERR!   CC(target) Release/obj.target/libusb/libusb/libusb/core.o
npm ERR!   CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
npm ERR!   CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
npm ERR!   CC(target) Release/obj.target/libusb/libusb/libusb/io.o
npm ERR!   CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
npm ERR!   CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
npm ERR!   CC(target) Release/obj.target/libusb/libusb/libusb/os/events_posix.o
npm ERR!   CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
npm ERR!   CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
npm ERR!   CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
npm ERR! rm -f Release/obj.target/usb.a Release/obj.target/usb.a.ar-file-list; mkdir -p `dirname Release/obj.target/usb.a`
npm ERR! ar crs Release/obj.target/usb.a @Release/obj.target/usb.a.ar-file-list
npm ERR!   COPY Release/usb.a
npm ERR!   CXX(target) Release/obj.target/usb_bindings/src/node_usb.o
npm ERR! make: Leaving directory '/opt/pmc/global-gateway-server/node_modules/usb/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.1
npm ERR! gyp info using node@18.17.1 | linux | arm
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.17.1/node-v18.17.1-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.17.1/node-v18.17.1-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v18.17.1/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.17.1/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/pmc/global-gateway-server/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/pmc/global-gateway-server/node_modules/usb/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/pmc/global-gateway-server/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/build/.cache/node-gyp/18.17.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/build/.cache/node-gyp/18.17.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/pmc/global-gateway-server/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/build/.cache/node-gyp/18.17.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/opt/pmc/global-gateway-server/node_modules/usb',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/node_usb.h:15,
npm ERR!                  from ../src/node_usb.cc:1:
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:317:3: error: 'node_api_nogc_env' does not name a type
npm ERR!   317 |   node_api_nogc_env _env;
npm ERR!       |   ^~~~~~~~~~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:325:29: error: expected ')' before 'env'
npm ERR!   325 |   BasicEnv(node_api_nogc_env env);
npm ERR!       |           ~                 ^~~~
npm ERR!       |                             )
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:326:12: error: expected type-specifier before 'node_api_nogc_env'
npm ERR!   326 |   operator node_api_nogc_env() const;
npm ERR!       |            ^~~~~~~~~~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h: In member function 'bool Napi::BasicEnv::operator==(const Napi::BasicEnv&) const':
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:335:12: error: '_env' was not declared in this scope
npm ERR!   335 |     return _env == other._env;
npm ERR!       |            ^~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:335:26: error: 'const class Napi::BasicEnv' has no member named '_env'
npm ERR!   335 |     return _env == other._env;
npm ERR!       |                          ^~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h: In member function 'bool Napi::BasicEnv::operator==(std::nullptr_t) const':
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:338:12: error: '_env' was not declared in this scope
npm ERR!   338 |     return _env == nullptr;
npm ERR!       |            ^~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h: At global scope:
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:2467:32: error: 'node_api_nogc_env' has not been declared
npm ERR!  2467 |   static void FinalizeCallback(node_api_nogc_env env, void* data, void* hint);
npm ERR!       |                                ^~~~~~~~~~~~~~~~~
npm ERR! In file included from /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:3257,
npm ERR!                  from ../src/node_usb.h:15,
npm ERR!                  from ../src/node_usb.cc:1:
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:38:13: error: variable or field 'default_basic_finalizer' declared void
npm ERR!    38 | inline void default_basic_finalizer(node_api_nogc_env /*env*/,
npm ERR!       |             ^~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:38:37: error: 'node_api_nogc_env' was not declared in this scope
npm ERR!    38 | inline void default_basic_finalizer(node_api_nogc_env /*env*/,
npm ERR!       |                                     ^~~~~~~~~~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:39:37: error: expected primary-expression before 'void'
npm ERR!    39 |                                     void* data,
npm ERR!       |                                     ^~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:40:37: error: expected primary-expression before 'void'
npm ERR!    40 |                                     void* /*hint*/) {
npm ERR!       |                                     ^~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:49:11: error: 'node_api_nogc_finalize' has not been declared
npm ERR!    49 |           node_api_nogc_finalize finalizer = default_basic_finalizer<FreeType>>
npm ERR!       |           ^~~~~~~~~~~~~~~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:49:46: error: 'default_basic_finalizer' was not declared in this scope
npm ERR!    49 |           node_api_nogc_finalize finalizer = default_basic_finalizer<FreeType>>
npm ERR!       |                                              ^~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:49:78: error: expected primary-expression before '>>' token
npm ERR!    49 |           node_api_nogc_finalize finalizer = default_basic_finalizer<FreeType>>
npm ERR!       |                                                                              ^~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:49:78: error: expected '>' before '>>' token
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h: In function 'napi_status Napi::details::AttachData(napi_env, napi_value, FreeType*, void*)':
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:73:47: error: 'finalizer' was not declared in this scope
npm ERR!    73 |   status = napi_add_finalizer(env, obj, data, finalizer, hint, nullptr);
npm ERR!       |                                               ^~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h: At global scope:
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:198:30: error: 'node_api_nogc_env' has not been declared
npm ERR!   198 |   static inline void Wrapper(node_api_nogc_env env,
npm ERR!       |                              ^~~~~~~~~~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:233:38: error: 'node_api_nogc_env' has not been declared
npm ERR!   233 |   static inline void WrapperWithHint(node_api_nogc_env env,
npm ERR!       |                                      ^~~~~~~~~~~~~~~~~
npm ERR! In file included from /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:3257,
npm ERR!                  from ../src/node_usb.h:15,
npm ERR!                  from ../src/node_usb.cc:1:
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:579:8: error: ISO C++ forbids declaration of 'BasicEnv' with no type [-fpermissive]
npm ERR!   579 | inline BasicEnv::BasicEnv(node_api_nogc_env env) : _env(env) {}
npm ERR!       |        ^~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:579:1: warning: inline variables are only available with '-std=c++17' or '-std=gnu++17'
npm ERR!   579 | inline BasicEnv::BasicEnv(node_api_nogc_env env) : _env(env) {}
npm ERR!       | ^~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:579:8: error: 'int Napi::BasicEnv::BasicEnv' is not a static data member of 'class Napi::BasicEnv'
npm ERR!   579 | inline BasicEnv::BasicEnv(node_api_nogc_env env) : _env(env) {}
npm ERR!       |        ^~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:579:27: error: 'node_api_nogc_env' was not declared in this scope
npm ERR!   579 | inline BasicEnv::BasicEnv(node_api_nogc_env env) : _env(env) {}
npm ERR!       |                           ^~~~~~~~~~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:581:27: error: expected type-specifier before 'node_api_nogc_env'
npm ERR!   581 | inline BasicEnv::operator node_api_nogc_env() const {
npm ERR!       |                           ^~~~~~~~~~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h: In constructor 'Napi::Env::Env(napi_env)':
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:585:45: error: no matching function for call to 'Napi::BasicEnv::BasicEnv(napi_env__*&)'
npm ERR!   585 | inline Env::Env(napi_env env) : BasicEnv(env) {}
npm ERR!       |                                             ^
npm ERR! In file included from ../src/node_usb.h:15,
npm ERR!                  from ../src/node_usb.cc:1:
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:315:7: note: candidate: 'constexpr Napi::BasicEnv::BasicEnv()'
npm ERR!   315 | class BasicEnv {
npm ERR!       |       ^~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:315:7: note:   candidate expects 0 arguments, 1 provided
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:315:7: note: candidate: 'constexpr Napi::BasicEnv::BasicEnv(const Napi::BasicEnv&)'
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:315:7: note:   no known conversion for argument 1 from 'napi_env' {aka 'napi_env__*'} to 'const Napi::BasicEnv&'
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:315:7: note: candidate: 'constexpr Napi::BasicEnv::BasicEnv(Napi::BasicEnv&&)'
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:315:7: note:   no known conversion for argument 1 from 'napi_env' {aka 'napi_env__*'} to 'Napi::BasicEnv&&'
npm ERR! In file included from /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:3257,
npm ERR!                  from ../src/node_usb.h:15,
npm ERR!                  from ../src/node_usb.cc:1:
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h: In member function 'Napi::Env::operator napi_env() const':
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:588:31: error: '_env' was not declared in this scope
npm ERR!   588 |   return const_cast<napi_env>(_env);
npm ERR!       |                               ^~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h: In member function 'void Napi::BasicEnv::SetInstanceData(T*) const':
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:669:7: error: '_env' was not declared in this scope
npm ERR!   669 |       _env,
npm ERR!       |       ^~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h: In member function 'void Napi::BasicEnv::SetInstanceData(DataType*, HintType*) const':
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:682:7: error: '_env' was not declared in this scope
npm ERR!   682 |       _env,
npm ERR!       |       ^~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h: In member function 'T* Napi::BasicEnv::GetInstanceData() const':
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:696:47: error: '_env' was not declared in this scope
npm ERR!   696 |   napi_status status = napi_get_instance_data(_env, &data);
npm ERR!       |                                               ^~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h: At global scope:
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:5021:13: error: variable or field 'FinalizeCallback' declared void
npm ERR!  5021 | inline void ObjectWrap<T>::FinalizeCallback(node_api_nogc_env env,
npm ERR!       |             ^~~~~~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:5021:45: error: 'node_api_nogc_env' was not declared in this scope
npm ERR!  5021 | inline void ObjectWrap<T>::FinalizeCallback(node_api_nogc_env env,
npm ERR!       |                                             ^~~~~~~~~~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:5022:45: error: expected primary-expression before 'void'
npm ERR!  5022 |                                             void* data,
npm ERR!       |                                             ^~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:5023:45: error: expected primary-expression before 'void'
npm ERR!  5023 |                                             void* /*hint*/) {
npm ERR!       |                                             ^~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h: In instantiation of 'napi_status Napi::CreateFunction(napi_env, const char*, napi_callback, CbData*, napi_value__**) [with CbData = Napi::details::CallbackData<Napi::Value (*)(const Napi::CallbackInfo&), Napi::Value>; napi_env = napi_env__*; napi_callback = napi_value__* (*)(napi_env__*, napi_callback_info__*); napi_value = napi_value__*; napi_callback_info = napi_callback_info__*]':
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:2566:21:   required from 'static Napi::Function Napi::Function::New(napi_env, Callable, const char*, void*) [with Callable = Napi::Value (*)(const Napi::CallbackInfo&); napi_env = napi_env__*]'
npm ERR! ../src/node_usb.cc:63:72:   required from here
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:2509:39: error: no matching function for call to 'AttachData(napi_env__*&, napi_value__*&, Napi::details::CallbackData<Napi::Value (*)(const Napi::CallbackInfo&), Napi::Value>*&)'
npm ERR!  2509 |     status = Napi::details::AttachData(env, *result, data);
npm ERR!       |              ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
npm ERR! In file included from /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:3257,
npm ERR!                  from ../src/node_usb.h:15,
npm ERR!                  from ../src/node_usb.cc:1:
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:50:20: note: candidate: 'template<class FreeType, <declaration error> > napi_status Napi::details::AttachData(napi_env, napi_value, FreeType*, void*)'
npm ERR!    50 | inline napi_status AttachData(napi_env env,
npm ERR!       |                    ^~~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:50:20: note:   template argument deduction/substitution failed:
npm ERR! In file included from /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:3257,
npm ERR!                  from ../src/node_usb.h:15,
npm ERR!                  from ../src/node_usb.cc:1:
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h: In instantiation of 'napi_status Napi::CreateFunction(napi_env, const char*, napi_callback, CbData*, napi_value__**) [with CbData = Napi::details::CallbackData<UVQueue<T>::start<HotPlug*>::<lambda(const Napi::CallbackInfo&)>, void>; napi_env = napi_env__*; napi_callback = napi_value__* (*)(napi_env__*, napi_callback_info__*); napi_value = napi_value__*; napi_callback_info = napi_callback_info__*]':
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:2566:21:   required from 'static Napi::Function Napi::Function::New(napi_env, Callable, const char*, void*) [with Callable = UVQueue<T>::start<HotPlug*>::<lambda(const Napi::CallbackInfo&)>; napi_env = napi_env__*]'
npm ERR! ../src/uv_async_queue.h:14:60:   required from 'void UVQueue<T>::start(Napi::Env) [with T = HotPlug*]'
npm ERR! ../src/node_usb.cc:145:45:   required from here
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:2509:39: error: no matching function for call to 'AttachData(napi_env__*&, napi_value__*&, Napi::details::CallbackData<UVQueue<T>::start<HotPlug*>::<lambda(const Napi::CallbackInfo&)>, void>*&)'
npm ERR!  2509 |     status = Napi::details::AttachData(env, *result, data);
npm ERR!       |              ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
npm ERR! In file included from /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi.h:3257,
npm ERR!                  from ../src/node_usb.h:15,
npm ERR!                  from ../src/node_usb.cc:1:
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:50:20: note: candidate: 'template<class FreeType, <declaration error> > napi_status Napi::details::AttachData(napi_env, napi_value, FreeType*, void*)'
npm ERR!    50 | inline napi_status AttachData(napi_env env,
npm ERR!       |                    ^~~~~~~~~~
npm ERR! /opt/pmc/global-gateway-server/node_modules/usb/node_modules/node-addon-api/napi-inl.h:50:20: note:   template argument deduction/substitution failed:
npm ERR! make: *** [usb_bindings.target.mk:124: Release/obj.target/usb_bindings/src/node_usb.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/pmc/global-gateway-server/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.15.123.1-microsoft-standard-WSL2
npm ERR! gyp ERR! command "/opt/node/bin/node" "/opt/pmc/global-gateway-server/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /opt/pmc/global-gateway-server/node_modules/usb
npm ERR! gyp ERR! node -v v18.17.1
npm ERR! gyp ERR! node-gyp -v v9.4.1
npm ERR! gyp ERR! not ok
```

**Comment by NickNaso** [comment]
Hi everybody, it seems that the problem is on Linux, I tried to compile:
- https://github.com/dachev/node-cld
- https://github.com/node-usb/node-usb
- https://github.com/microsoft/vscode-policy-watcher
and it seems to work weel on `macOS`. Can someone confirm that is a proble only on Linux?

**Comment by ddolcimascolo** [comment]
As mentioned I'm on Linux, yes.

**Comment by sallar** [comment]
Have the same issue. My builds started failing on Windows since 1.10.2024 because I had `"^8.1.0"` in my `package.json` which automatically got updated to 8.2.0.

**Comment by Badisi** [comment]
Having the same issue after upgrading to `v8.2.0` (everything worked fine with `v8.1.0`).

I'm using `node v20.17.0` and it fails on every platforms:
- Darwin 23.6.0
- Linux 6.8.0-1014-azure
- Windows_NT 10.0.20348

**Comment by mhdawson** [comment]
@nodejs/node-api, I think we might want to revert the changes in 8.2 and then investigate. What do you think?

**Comment by NickNaso** [comment]
I think tha twe can set on `npm` the version `8.1.0` as `latest` then we can work on fix the problem in the `8.2.0` and when we solve publishing the new `8.2.1` it will became the new `latest`.

**Comment by NickNaso** [comment]
The problem is that the type `node_api_nogc_env` is available from the following Node.js versions or above:
- `>= v22.0.0`
- `>= v20.12.0`
- `>= v18.20.0`

**Comment by Badisi** [comment]
@NickNaso, that's weird because I can reproduce the issue:
- locally with a NodeJS `v20.15.1` on macOS
- on github with a NodeJS `v20.17.0` on macOS, linux and windows
<img width="1511" alt="Screen Shot 2024-10-02 at 22 58 36" src="https://github.com/user-attachments/assets/8050a10c-912e-4ec0-9cf9-89694caae412">

**Comment by NickNaso** [comment]
@Badisi is your project public?

**Comment by NickNaso** [comment]
I created a repo where I'm using the `node-api-headers` to include the right headers of Node-API and the compilation works well for it does not matter wchich version of Node.js you have. This is the repo https://github.com/NickNaso/node-addon-api-issue-1584. 
In this way the build will be indipendent from the Node.js version used. We could add `node-api-headers` to `node-addon-api` and use it to set the `include_dir` but the best thing is to add it to `node-gyp` and when we build a Node-API addon we use the `node-api-headers` like `cmake-js` already do https://github.com/cmake-js/cmake-js/blob/master/lib/cMake.js#L247

**Comment by legendecas** [comment]
I tagged node-addon-api@8.1.0 as the latest to reduce the impact.

**Comment by richardlau** [comment]
At least in the screenshot provided by @Badisi, passing `--target=12.0.0` to node-gyp would cause node-gyp to compile against the headers for Node.js 12.0.0.

**Comment by ddolcimascolo** [comment]
Hi guys, still broken? Any information you may need from me, feel free to ask.

Cheers,
David

**Comment by mhdawson** [comment]
@ddolcimascolo a fix is being worked in https://github.com/nodejs/node-addon-api/pull/1585, you could test that out and confirm that it resolves the issue for you. 

We have also changed the latest to 8.1 so that people pull that instead of 8.2 until the issue is resolved.

**Comment by ddolcimascolo** [comment]
Thx for the update

**Comment by ddolcimascolo** [comment]
Thx for fixing. Renovate picked up and merged v8.2.1 👍
