### ISSUE TITLE
npmjs provided package did not match github code

### ISSUE THREAD

**Issue by stephan-wolf-ais** [nodejs/node-addon-api#586]
The package version 1.7.1 published on npmjs.org is different from github version 1.7.1.

**Comment by NickNaso** [comment]
Hi @stephan-wolf-ais ,
I checkout the branch tagged as **[1.7.1](https://github.com/nodejs/node-addon-api/tree/1.7.1)** and the module `node-addon-api` from npm and I cannot able to fund any differences. Could you please be more specific about the differences that you found and help me to find the problem more quickly?

**Comment by stephan-wolf-ais** [comment]
I installed the module from npm. npm says to me installing version 1.7.1 but the source code from an older version. Also npmjs.org shows in the version history version 1.7.1 was uploaded 3 month ago!

**Comment by NickNaso** [comment]
@stephan-wolf-ais I went on the source code  and compared al the files and I only found the difference in the `package.json` file because it has a different formatting and we will provide to how the `package.json` is formatted in the next release https://github.com/nodejs/node-addon-api/issues/570#issue-510548688

**Comment by stephan-wolf-ais** [comment]
I zipped the npm downloaded directory. 
[node-addon-api.tar.gz](https://github.com/nodejs/node-addon-api/files/3808591/node-addon-api.tar.gz)

As you can see i.e. the napi.h is from an older version. There is no NAPI_EXPERIMENTAL preprocessor directives.

And please have a look in the versions history on npmjs.org.

**Comment by stephan-wolf-ais** [comment]
I set up a different system and install node-addon-api with the same result.

**Comment by NickNaso** [comment]
Hi @stephan-wolf-ais ,
now I think to understand the problem. You are comparing what is in the **master** branch with what you downloaded from **npm** and it's not right. In the master branch usually there are new features, fixes, so the code is different from what was published on **npm**. To compare what is on **npm** you have to use the code in the release https://github.com/nodejs/node-addon-api/archive/1.7.1.zip or switch from the **master** branch to the commit tagged like 1.7.1 https://github.com/nodejs/node-addon-api/tree/1.7.1.

**Comment by stephan-wolf-ais** [comment]
So I misunderstand the info line about "24 commits to the master..." Sorry about that. Can you tell me when the latest changes will be released?

**Comment by NickNaso** [comment]
We are working on the new release to be precise the version 2.0.0 you can follow all the works in the following issue https://github.com/nodejs/node-addon-api/issues/570. I'm not sure about the exact timing so I suggest to subscribe to the issue I reported so you will be reported when the new version will be published.

**Comment by stephan-wolf-ais** [comment]
Thanks a lot for your work. I trying to get our project to compile with version 1.7.1. But I get the always the same error: 

/home/admin/.node-red/node_modules/node-addon-api/napi.h:825:45: error: ‘napi_bigint64_array’ was not declared in this scope
         : std::is_same<T, int64_t>::value ? napi_bigint64_array

Where is the type napi_bigint64_array declared? I can not find it.

**Comment by legendecas** [comment]
Did you define `NAPI_EXPERIMENTAL` in your project? napi_bigint and its related APIs should only be enabled on `NAPI_EXPERIMENTAL` defined. And yet napi_bigint APIs were only available after Node.js v10.

**Comment by stephan-wolf-ais** [comment]
I checked the node.js version as well. The failing system is v8. That is the root cause. Damn 3 days of work for nothing.
