### ISSUE TITLE
test failure: test/run_script.js:31:14

### ISSUE THREAD

**Issue by legendecas** [nodejs/node-addon-api#640]
Test failed since ffc71edd54e98607e29c2b22e365e551c953d628 on Node.js v6.

```
Test failed: JavaScript, but not a string
/home/travis/build/nodejs/node-addon-api/test/testUtil.js:17
        throw e;
        ^
TypeError: expected.call is not a function
    at expectedException (assert.js:299:19)
    at innerThrows (assert.js:343:8)
    at Function.throws (assert.js:350:3)
    at Array.testUtil.runGCTests (/home/travis/build/nodejs/node-addon-api/test/run_script.js:31:14)
    at runGCTests (/home/travis/build/nodejs/node-addon-api/test/testUtil.js:14:17)
    at runGCTests (/home/travis/build/nodejs/node-addon-api/test/testUtil.js:11:7)
    at Immediate.setImmediate (/home/travis/build/nodejs/node-addon-api/test/testUtil.js:21:9)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

I'd believe it's an API issue that `assert.throws` support objects as the second parameter since v9.2 (which has been backported to v8).
